---
- name: Prompt for Windows password if needed
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "windows_password"
      prompt: "Enter Password:"
      private: yes
  tasks:
    - name: Store password for later use
      set_fact:
        stored_password: "{{ windows_password }}"
      when: windows_password | length > 0

- name: Deploy to a remote machine
  hosts: all
  gather_facts: yes
  
  vars:
    ansible_password: "{{ hostvars['localhost']['stored_password'] | default(omit) }}"
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Deploy Kali machine
      ansible.builtin.include_role:
        name: Linux/Kali
      when: machine == "Kali"
    
    - name: Deploy Windows base configuration
      ansible.builtin.include_role:
        name: Windows/NewJob
      when: machine == "Windows"
    
    - name: Deploy Windows Dev
      ansible.builtin.include_role:
        name: Windows/Dev
      when: machine == "WindowsDev"
    
    - name: Fail if no valid machine type specified
      ansible.builtin.fail:
        msg: "Invalid machine type. Please specify machine=Kali, machine=Windows, or machine=WindowsDev"
      when: machine not in ["Kali", "Windows", "WindowsDev"]
