---
- name: Create tool and list directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ Tools }}"
    - "{{ Tools_Windows }}"
    - "{{ Tools_Linux }}"
    - "{{ Tools_Generic }}"
    - "{{ Lists }}"
