---
- name: Checking for {{ item.split('/') | last }}
  ansible.builtin.stat:
    path: "{{ dir }}/{{ item.split('/') | last }}"
  register: git_path

- name: Cloning {{ item.split('/') | last }}
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ dir }}/{{ item.split('/') | last }}"
  when: not git_path.stat.exists
