---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install apt packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ InitialPackages }}"
  become: true

- name: Install python packages via pipx
  community.general.pipx:
    name: "{{ item }}"
  loop: "{{ PipInstalls }}"

- name: Ensure pipx bin dir is in PATH
  ansible.builtin.command:
    cmd: pipx ensurepath
  changed_when: false
