---
- ansible.builtin.include_tasks: installs.yml
- ansible.builtin.include_tasks: ghostty.yml
- ansible.builtin.include_tasks: terminal.yml
- ansible.builtin.include_tasks: folders.yml

############# Lists
- ansible.builtin.include_tasks: git.yml
  vars:
    dir: "{{ Lists }}"
  loop: "{{ ListsGit }}"

############# Tooling - Git
- ansible.builtin.include_tasks: git.yml
  vars:
    dir: "{{ Tools_Windows }}"
  loop: "{{ WindowsToolsGit }}"

- ansible.builtin.include_tasks: git.yml
  vars:
    dir: "{{ Tools_Linux }}"
  loop: "{{ LinuxToolsGit }}"

- ansible.builtin.include_tasks: git.yml
  vars:
    dir: "{{ Tools_Generic }}"
  loop: "{{ GenericToolsGit }}"

############# Tooling - Downloads
- ansible.builtin.include_tasks: download.yml
  vars:
    dir: "{{ Tools_Windows }}"
  loop: "{{ WindowsToolsDownloads }}"

- ansible.builtin.include_tasks: download.yml
  vars:
    dir: "{{ Tools_Linux }}"
  loop: "{{ LinuxToolsDownloads }}"

############# Tooling - Compressed
- ansible.builtin.include_tasks: compressed.yml
  vars:
    dir: "{{ Tools_Windows }}"
  loop: "{{ WindowsToolsCompressed }}"

- ansible.builtin.include_tasks: docker_images.yml
  loop: "{{ DockerImages }}"

- ansible.builtin.include_tasks: snmp.yml
- ansible.builtin.include_tasks: fix_metasploit.yml
- ansible.builtin.include_tasks: tailscale.yml
- ansible.builtin.include_tasks: cleanup.yml
# - ansible.builtin.include_tasks: reboot.yml
