---
- name: Ensure /etc/snmp/snmp.conf exists
  become: true
  ansible.builtin.file:
    path: /etc/snmp/snmp.conf
    state: touch
    mode: '0644'

- name: Uncomment mibdirs line in snmp.conf
  become: true
  ansible.builtin.replace:
    path: /etc/snmp/snmp.conf
    regexp: '^#(mibdirs /usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf)'
    replace: '\1'
